name: Tests

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Install tox
        run: uv sync --only-dev
      - name: Run Ruff
        run: uv run ruff check
      - name: Run Mypy
        run: uv run mypy laima/ examples/ tests/
      - name: Run Unittests
        run: uv run pytest tests/unit/
